#! /bin/sh
set -e

cat > /target/etc/apt/sources.list.d/estuary.list <<EOF
## Estuary App Overlay
deb ftp://repoftp:repopushez7411@117.78.41.188/releases/5.0/debian/ estuary-5.0 main
deb-src ftp://repoftp:repopushez7411@117.78.41.188/releases/5.0/debian/ estuary-5.0 main
## Estuary Kernel Overlay
deb ftp://repoftp:repopushez7411@117.78.41.188/releases/5.2/debian/ estuary-5.2 main
deb-src ftp://repoftp:repopushez7411@117.78.41.188/releases/5.2/debian/ estuary-5.2 main
EOF

cp /usr/share/estuary/estuaryrepo.key /target/tmp/key.pub
in-target apt-key add "/tmp/key.pub"
in-target apt-get update -q || true
apt-install linux-image-estuary-arm64

